---
language: ruby
bundler_args: --without development
cache: bundler
before_install: rm Gemfile.lock || true
rvm:
  - 2.1.1
  - 1.9.3
script: bundle exec rake spec
env:
  - PUPPET_VERSION="~> 3.6.0"
  - PUPPET_VERSION="~> 3.7.0"
