---
language: ruby

rvm:
  - 2.0.0
  - 2.1.0
  - 2.1.1

env:
  matrix:
    - PUPPET_GEM_VERSION="~> 3.4.0"
    - PUPPET_GEM_VERSION="~> 3.5.1"
    - PUPPET_GEM_VERSION="~> 3.6.0"
    - PUPPET_GEM_VERSION="~> 3.7.0"

sudo: false

script: 'bundle exec rake validate && bundle exec rake lint && SPEC_OPTS="--format documentation" bundle exec rake spec'

matrix:
  fast_finish: true
  exclude:
    - rvm: 2.1.0
      env: PUPPET_GEM_VERSION="~> 3.4.0"
  exclude:
    - rvm: 2.1.1
      env: PUPPET_GEM_VERSION="~> 3.4.0"

notifications:
  email: false
