HOSTS:
  centos-7-x86_86-master:
    roles:
      - master
      - dashboard
      - database
      - agent
    platform: el-7-x86_64
    template: Delivery/Quality Assurance/Templates/vCloud/centos-7-x86_64
    hypervisor: vcloud
  centos-7-x86_86-agent:
    roles:
      - agent
      - default
    platform: el-7-x86_64
    template: Delivery/Quality Assurance/Templates/vCloud/centos-7-x86_64
    hypervisor: vcloud
CONFIG:
  nfs_server: none
  consoleport: 443
  datastore: instance0
  folder: Delivery/Quality Assurance/Enterprise/Dynamic
  resourcepool: delivery/Quality Assurance/Enterprise/Dynamic
  pooling_api: http://vmpooler.delivery.puppetlabs.net/
  forge_host: api-module-staging.puppetlabs.com